name: i18n_extension
description: Translation and Internationalization (i18n) for Flutter. Easy to use for both large and small projects. Uses Dart extensions to reduce boilerplate.
version: 8.0.0
homepage: https://github.com/marcglasberg/i18n_extension
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  sprintf: ^7.0.0
  args: ^2.3.1
  equatable: ^2.0.5
  intl: ^0.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^5.3.1
  gettext_parser: ^0.2.0
  flutter_test:
    sdk: flutter

